modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/MisterPeModder/ShulkerBoxTooltip/issues"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/shulkerboxtooltip/"
license = "MIT"

[[mods]]
modId = "shulkerboxtooltip"
version = "${version}"
displayName = "ShulkerBoxTooltip"
authors = "MisterPeModder"
description = "What's in my shulker box?"
logoFile = "icon.png"

[[dependencies.shulkerboxtooltip]]
modId = "forge"
mandatory = true
versionRange = "[41.0.15,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.shulkerboxtooltip]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.shulkerboxtooltip]]
modId = "cloth_config"
mandatory = true
versionRange = "[10.0.0,)"
ordering = "NONE"
side = "BOTH"
